### PR TITLE
Fix 404 for loading source maps with digests in url

### PR DESCRIPTION
**Pull request by theodorton**
See reported issue #193.

Bisecting on v0.8 shows regression introduced in #171.

### CODE REVIEW

**Comment by searls** [comment]
Just got bit by this after running `bundle update` -- it'd be awesome if you could cut a patch release, because this 404 was a bit confusing to figure out before visiting the propshaft's commit history

**Comment by dixpac** [comment]
@dhh @brenogazzola can we release the latest changes? I've just spend 2 hours trying to figure out why source-maps are not working on 0.9.0 🙏

**Comment by dhh** [comment]
Will cut a release.

**Comment by dhh** [comment]
0.9.1 has been released: https://github.com/rails/propshaft/releases/tag/v0.9.1

**Pull request merged**
