### PR TITLE
CI: Include Ruby 3.1

### PR DESCRIPTION
**Pull request by olleolleolle**
MiniTest has released. https://rubygems.org/gems/minitest/versions/5.15.0 Any Ruby < 4.0.

This PR adds ~back `head` and~ Ruby `3.1`.

### CODE REVIEW

**Comment by dhh** [comment]
3,1 seems to be failing.

**Comment by olleolleolle** [comment]
Looks a bit like a Gemfile can solve this:   

```
Fetching gem metadata from https://rubygems.org/..........
  nokogiri-1.12.5-x86_64-linux requires ruby version < 3.1.dev, >= 2.5, which is
  incompatible with the current version, ruby 3.1.1p18
  Took   2.70 seconds
```

**Comment by olleolleolle** [comment]
@dhh I guess this small Gemfile.lock update does the trick.

**Comment by dhh** [comment]
Now the failure is something else.

**Comment by olleolleolle** [comment]
Alright!

>   nokogiri-1.13.3-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is
>   incompatible with the current version, ruby 3.2.0p-1

**Comment by dhh** [comment]
"3 successful and 1 failing checks", isn't head supposed to just warn rather than block?

**Comment by olleolleolle** [comment]
@dhh I have unsuccessfully looked for an "allow failures" analogue in GH Actions.

**Comment by dhh** [comment]
If not, maybe just remove head for now 👍

**Comment by olleolleolle** [comment]
@dhh Perhaps this can be squashed on merge?

**Pull request merged**
