### PR TITLE
README update - avoid isses related to browser cache during development

### PR DESCRIPTION
**Pull request by equivalent**
related to hours spent figuring out  https://github.com/rails/propshaft/issues/90 :)

### CODE REVIEW

**Comment by dhh** [comment]
@brenogazzola We should think about a better solution here. But one does not immediately come to mind!

**Comment by brenogazzola** [comment]
Since the server is only used in development we could change the cache-control header to no cache or no store for css files. I’ll test it and see what happens.

**Comment by brenogazzola** [comment]
Possible PR to fix this: #96

**Comment by brenogazzola** [comment]
I've been testing this our outside of rails, and it seems this is a normal problem with the `@import` rule. Browsers cache the files and don't notice if you change the `@import` inside them. I thought they might skip caching or something like that, but no. So we can't cheat and copy their behavior. 

All solutions I've tried so far get stuck in one of two:
1 - You need stable fingerprints in production (no cache busting on every deploy)
2 - You might have multiple levels of `@import` or cyclical `@import`

**Comment by dhh** [comment]
Could we simply send no-cache headers in development?

**Comment by equivalent** [comment]
Yes in fact the no-cache header does the trick ! 🎉. Creating new PR with solution => https://github.com/rails/propshaft/pull/124

closing this one

**Pull request closed without merging**
