### PR TITLE
Digests of files that can have dependencies on other files in the load path need to reflect those dependencies

### PR DESCRIPTION
**Pull request by dhh**
CSS files that reference other CSS files via `@import` or images via `url()` need to have their digest reflect changes in the dependencies. This PR adds that by including the content of all dependencies in the calculation for such assets with dependencies.

This takes some inspiration from https://github.com/rails/propshaft/pull/175 but avoids the dependency tree tracking.

### CODE REVIEW

**Comment by wlipa** [comment]
For some reason, I'm not getting digested assets in CSS files with this.  I do get digests from the asset helpers though.

**Comment by dhh** [comment]
@wlipa What do you mean exactly? That `@import url` isn't being replaced with a digested url?

**Comment by dhh** [comment]
Ah, I see the problem.

**Comment by wlipa** [comment]
In content_with_compile_dependencies, the references will need to be returned in a stable order in order for digests to be stable.  Maybe they are if it's based on source code order?  Not 100% sure on merging.

**Comment by dhh** [comment]
Should be stable given the scan will always return them in order. But good question about set guaranteeing a stable order. Will investigate.

**Comment by dhh** [comment]
As far as I can tell, since Ruby 2.5, the insert order is guaranteed in a set, and that includes merging. So we should be good.

**Comment by wlipa** [comment]
This is checking out for me now.  👍🏼

**Comment by dhh** [comment]
Thanks for your help with this, @wlipa. Got some good inspiration for this approach from your work, and I think we ended up in a nice place without complicating the domain model much.

**Comment by dhh** [comment]
Fixes https://github.com/rails/propshaft/issues/123 and https://github.com/rails/propshaft/issues/90. Closes #175.

**Comment by wlipa** [comment]
Yeah sounds good.  It's definitely simpler.  The only thing I noticed that's a bit of a trade-off is reading all the dependent assets into memory to do that sum.  Could be a lot with big images.  But maybe it's not that much of a problem in practice.

**Comment by dhh** [comment]
Yeah but we read them into memory anyway to digest them individually. Although of course it's perhaps a higher peak if a single css file references a ton of images. Still, doubt it's an issue. Your images shouldn't be that big in the first place if referenced by css!

**Pull request merged**
