### PR TITLE
Do not mount the server if public_file_server is not enabled

### PR DESCRIPTION
**Pull request by aaronjensen**
There wasn't an obvious place to test this, so I omitted the test.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This will break the library since the public server is never enabled in development or tests. This is using the wrong config. You actually wants the propshaft server disabled when using the public server, not enabled. I’m going to revert.

**Comment by aaronjensen** [comment]
@rafaelfranca I'm not sure I follow, what am I missing? Rails enables it by default in test:

```
  # Configure public file server for tests with Cache-Control for performance.
  config.public_file_server.enabled = true
  config.public_file_server.headers = {
    "Cache-Control" => "public, max-age=#{1.hour.to_i}"
  }
```

That's in `test.rb` of a newly generated app.

**Comment by rafaelfranca** [comment]
True. `public_file_server` controls the `ActionDispatch::Static` server, which you probably want enable in production even though you don't want the Propshaft server there, for example in a heroku setup. We should be using a different option. spockets users `config.assets.compile`. Since Propshaft doesn't compile, I think we should use a `config.assets.server`

**Comment by aaronjensen** [comment]
@rafaelfranca Got it, I forgot that propshaft gets out of the way upon precompile so its server is orthogonal. Thanks for setting us straight. I opened #61

**Pull request merged**
