### PR TITLE
Javascript compiler for ESM chunks

### LINKED ISSUE #48: Propshaft ESM Modules chunks not resolved correctly (works with sprockets-rails)
**application.js**:
Screenshot 2021-12-10 at 16 41 36

**app/views/layouts/application.html.erb**:
Screenshot 2021-12-10 at 16 46 20

**Google Chrome console / networks tab**
Screenshot 2021-12-10 at 16 42 55
Screenshot 2021-12-10 at 16 42 45

**Scenarios**:

Gemfile: Propshaft uncommented, sprockets-rails commented
`ESBUILD_MODULES=1 ./bin/dev`
Output: 🔴

Gemfile: Propshaft commented, sprockets-rails uncommented
`ESBUILD_MODULES=1 ./bin/dev`
Output: 🟢

Gemfile: Propshaft commented, sprockets-rails uncommented
`./bin/dev`
Output: 🟢

Gemfile: Propshaft uncommented, sprockets-rails commented
`./bin/dev`
Output: 🟢

Minimalist application to reproduce the issue: https://github.com/navidemad/PropshaftApp

### PR DESCRIPTION
**Pull request by brenogazzola**
Closes #48 

@navidemad Could you test this one please? Also, I haven't started using ESM modules yet, so I'm not too familiar with chunking, but it seems that a pure `import('file.js')` is also possible instead of `import {} from 'file.js'`?

### CODE REVIEW

**Comment by navidemad** [comment]
Could you test this one please?
✅ Yes it is working fine with this pull request, thanks for the quick PR 🔥

It seems that a pure import('file.js') is also possible instead of import {} from 'file.js' ? 
Yes but there is some more complicated format as you can see here :
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by brenogazzola** [comment]
Updated so it also handles `import 'chunk'` and `import('chunk')`

**Comment by dhh** [comment]
Should we extend this to deal with images and styles as well? Since those can also be imported?

But also, need to deal with compatibility with import maps. Where you don't want to rewrite.

**Comment by brenogazzola** [comment]
Importing CSS and images through javascript means tha page can’t render before JS executes, making it feel slower. Not supporting it out-of-the-box but allowing devs to add support through their own compiler feels like a good compromise and reduces our maintanance burden. 

I’ll take a look at how this behaves with import maps and see what needs changing.

**Comment by navidemad** [comment]
Any update on this PR ? 💯 
Merry Xmas 🥇

**Comment by brenogazzola** [comment]
Closed in favor of #55. An example of the esbuild configuration needed can be seem in #48

**Pull request closed without merging**
