### PR TITLE
Improve the registration of the Engines' assets path in propshaft

### PR DESCRIPTION
**Pull request by rafaelfranca**
I'm an not making the mistake to commit this without someone trying it.

@dhh or @rmacklin can you check if this works in the same way as before?

### CODE REVIEW

**Comment by rmacklin** [comment]
With the integration test from #20, this change [appears to pass CI](https://github.com/rmacklin/propshaft/runs/4418733714?check_suite_focus=true#step:4:11) - it doesn't break in the way that 66ce0f889377b81a28b1dd1fbe245868a047d46f broke the test suite (https://github.com/rails/propshaft/issues/41)

**Comment by brenogazzola** [comment]
I've tested it against a production app already running Sprockets and the output of `rake assets:reveal` is identical, so it seems its correctly picking the assets from gems.

**Comment by rafaelfranca** [comment]
Thank! @rmacklin can you open a new PR extracting the integrations tests from #20?

**Comment by rmacklin** [comment]
@rafaelfranca Done: #44

**Pull request merged**
